version: '3'
services:
  database:
    build: ./database
    ports:
      - "5432:5432"
  db-services:
    build: ./db-services
    environment:
      - POSTGRES_USER=admin
    volumes:
      - ./app/db-services:/opt/app/src
    ports:
      - "8000:8000"
    depends_on:
      - database
