version: '3'
services:
  database:
    build: ./database
    ports:
      - "5432:5432"
  app:
    build: ./app
    environment:
      - POSTGRES_USER=admin
    volumes:
      - ./app:/opt/app/src
    ports:
      - "8000:8000"
    depends_on:
      - database
